config/routes.rb
BootstrapStarter::Application.routes.draw do

	#--------------------------------
	# all resources should be within the scope block below
	#--------------------------------
	scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

		match '/admin', :to => 'admin#index', :as => :admin, :via => :get
    match '/user', :to => 'user#index', :as => :user, :via => :get
  
		 devise_for :users, :controllers => { :sessions => "users/sessions", :registrations => "users/registrations" }, :path_names => { :sign_up => "register" }

    namespace :admin do
      resources :users
    end

    resources :tenders
    resources :organizations

    match '/organization/search_procurer' => 'organizations#search_procurer'
    match '/organization/search' => 'organizations#search'
    match '/organization/getProcurers' => 'organizations#getProcurers'
    match '/organization/getSuppliers' => 'organizations#getSuppliers'
    match '/root/organization/search_procurer' => 'organizations#search_procurer'
    match '/root/organization/search' => 'organizations#search'

    match '/tender/search' => 'tenders#search'
    match '/tender/search_via_saved' => 'tenders#search_via_saved'
    match '/tender/download' => 'tenders#download'
    match '/organization/download_proc_tenders' => 'organizations#download_proc_tenders'
    match '/organization/download_org_tenders' => 'organizations#download_org_tenders'
    match '/tenders/index' => 'tenders#index'
    match '/procurer' => 'organizations#show_procurer'
    match '/watch_tender/subscribe' => 'watch_tender#subscribe'
    match '/watch_tender/unsubscribe' => 'watch_tender#unsubscribe'
    match '/cpv_tree/showCPVtree' => 'cpv_tree#showCPVTree'
    match ':controller/:action'
    match '/build_user_data', :to => 'root#build_user_data', :as => :build_user_data, :via => :get
    match '/generate_cpv_codes', :to => 'root#generate_cpv_codes', :as => :generate_cpv_codes, :via => :get
    match '/:locale' => 'root#index'		
    root :to => 'root#index'
	  
	end

	match '', :to => redirect("/#{I18n.default_locale}") # handles /
	
end

app/views/admin/index.html.erb
<% title t('.title') %>

  <% if current_user.role? :admin %>
   <div class="span4">
    <h2><%= t('.users_header')%></h3>
    <ul class="standard">
      <li>
        <%= link_to t('.view_users'), admin_users_path %>
      </li>
      <li>
        <%= link_to t('.new_users'), new_admin_user_path %>
      </li>
    </ul>
    <br>
    <%= button_to "manage global CPV Categories", {:action => "manageCPVs"} %>
    <br>
    <%= button_to "Manage risky cpv codes", {:controller => "cpv_tree", :action => "editCPVTree", :user_id => @userID} %>
  </div>
  <% end %>

app/views/admin/manageCPVs.html.erb
<h2>Global CPV categories</h2>
<br>
<%= render :partial => "user/cpvGroups"%>