config/routes.rb
BootstrapStarter::Application.routes.draw do

	#--------------------------------
	# all resources should be within the scope block below
	#--------------------------------
	scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

		match '/admin', :to => 'admin#index', :as => :admin, :via => :get
    match '/user', :to => 'user#index', :as => :user, :via => :get
  
		 devise_for :users, :controllers => { :sessions => "users/sessions", :registrations => "users/registrations" }, :path_names => { :sign_up => "register" }

    namespace :admin do
      resources :users
    end

    resources :tenders
    resources :organizations

    match '/organization/search_procurer' => 'organizations#search_procurer'
    match '/organization/search' => 'organizations#search'
    match '/organization/getProcurers' => 'organizations#getProcurers'
    match '/organization/getSuppliers' => 'organizations#getSuppliers'
    match '/root/organization/search_procurer' => 'organizations#search_procurer'
    match '/root/organization/search' => 'organizations#search'

    match '/tender/search' => 'tenders#search'
    match '/tender/search_via_saved' => 'tenders#search_via_saved'
    match '/tender/download' => 'tenders#download'
    match '/organization/download_proc_tenders' => 'organizations#download_proc_tenders'
    match '/organization/download_org_tenders' => 'organizations#download_org_tenders'
    match '/tenders/index' => 'tenders#index'
    match '/procurer' => 'organizations#show_procurer'
    match '/watch_tender/subscribe' => 'watch_tender#subscribe'
    match '/watch_tender/unsubscribe' => 'watch_tender#unsubscribe'
    match '/cpv_tree/showCPVtree' => 'cpv_tree#showCPVTree'
    match ':controller/:action'
    match '/build_user_data', :to => 'root#build_user_data', :as => :build_user_data, :via => :get
    match '/generate_cpv_codes', :to => 'root#generate_cpv_codes', :as => :generate_cpv_codes, :via => :get
    match '/:locale' => 'root#index'		
    root :to => 'root#index'
	  
	end

	match '', :to => redirect("/#{I18n.default_locale}") # handles /
	
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :watch_tenders
  has_many :searches
  has_many :cpvGroups
  has_many :procurer_watches
  has_many :supplier_watches
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
	# :registerable, :recoverable,
  devise  :registerable, :database_authenticatable,
         :rememberable, :trackable, :validatable, :recoverable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :id, :email, :password, :password_confirmation, :remember_me, :role

  validates :role, :presence => true

  def self.no_admins
    where("role != ?", ROLES[1])
  end


  # use role inheritence
  ROLES = %w[user admin]
  def role?(base_role)
    if base_role && ROLES.index(base_role.to_s)
      return ROLES.index(base_role.to_s) <= ROLES.index(role)
    end
    return false
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :requires_admin

  def requires_admin
    if current_user.role != 'admin'
      redirect_to "/"
    end
  end

  # GET /admin/users
  # GET /admin/users.json
  def index
    if current_user.role == User::ROLES[1]
      @users = User.all
    else
      @users = User.no_admins
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /admin/users/new
  # GET /admin/users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /admin/users/1/edit
  def edit
    @user = User.find(params[:id])
    if @user.role == User::ROLES[2] && current_user.role != User::ROLES[2]
      redirect_to admin_users_path
    end
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users_path, notice: t('app.msgs.success_created', :obj => t('app.common.user')) }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/users/1
  # PUT /admin/users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to admin_users_path, notice: t('app.msgs.success_updated', :obj => t('app.common.user')) }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :ok }
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :authenticate_user!
  include QueryHelper

  def index
    @watched_tenders = current_user.watch_tenders
    @watched_procurers = current_user.procurer_watches
    @watched_suppliers = current_user.supplier_watches
    @savedSearches = current_user.searches
    @cpvGroups = current_user.cpvGroups
    @userID = current_user.id
  end

  def save_search
    newSearch = Search.new
    newSearch.user_id = current_user.id
    newSearch.searchtype = params[:searchtype]
    newSearch.search_string = params[:search_string]
    newSearch.name = params[:name]
    newSearch.count = params[:count]
    newSearch.last_viewed = DateTime.now
    @savedName = params[:name]
    newSearch.save
    @thisSearchString = params[:search_string]
    @searchType = params[:searchtype]
  end

  def remove_search_from_account
    remove_search()
    redirect_to :back
  end

  def remove_search
    if params[:search_id]
      search = Search.find(params[:search_id])
      search.destroy
    else
      searchList = Search.where( :user_id => current_user.id, :searchtype => params[:searchtype], :name => params[:name], :search_string => params[:search_string] )
      searchList.each do |search|
        search.destroy
      end
      @thisSearchString = params[:search_string]
      @searchType = params[:searchtype]
    end
  end

  def unsubscribe_search
    @buttonID = params[:buttonID]
    search = Search.find(params[:search_id])
    search.email_alert = false
    search.save
    @searchID = search.id
  end

  def subscribe_search
    @buttonID = params[:buttonID]
    search = Search.find(params[:search_id])
    search.email_alert = true
    search.save
    @searchID = search.id
  end


  def add_procurer_watch
    watch_item = ProcurerWatch.new
    watch_item.procurer_id = params[:procurer_id]
    watch_item.user_id = current_user.id
    watch_item.save
    @procurer_watch_id = watch_item.id
  end

  def remove_procurer_watch
    watch = ProcurerWatch.find(params[:procurer_watch_id])
    @organization = Organization.find(watch.procurer_id)
    watch.destroy
  end

  def remove_procurer_watch_from_account
    remove_procurer_watch()
    redirect_to :back
  end

  def unsubscribe_procurer
    @buttonID = params[:buttonID]
    watch = ProcurerWatch.find(params[:procurer_watch_id])
    watch.email_alert = false
    watch.save
    @procurer_watch_id = watch.id
  end

  def subscribe_procurer
    @buttonID = params[:buttonID]
    watch = ProcurerWatch.find(params[:procurer_watch_id])
    watch.email_alert = true
    watch.save
    @procurer_watch_id = watch.id
  end

  def add_supplier_watch
    watch_item = SupplierWatch.new
    watch_item.supplier_id = params[:supplier_id]
    watch_item.user_id = current_user.id
    watch_item.save
    @supplier_watch_id = watch_item.id
  end
  
  def remove_supplier_watch
    watch = SupplierWatch.find(params[:supplier_watch_id])
    @organization = Organization.find(watch.supplier_id)
    watch.destroy
  end

  def remove_supplier_watch_from_account
    remove_supplier_watch()
    redirect_to :back
  end

  def unsubscribe_supplier
    @buttonID = params[:buttonID]
    watch = SupplierWatch.find(params[:supplier_watch_id])
    watch.email_alert = false
    watch.save
    @supplier_watch_id = watch.id
  end

  def subscribe_supplier
    @buttonID = params[:buttonID]
    watch = SupplierWatch.find(params[:supplier_watch_id])
    watch.email_alert = true
    watch.save
    @supplier_watch_id = watch.id
  end

  def add_tender_watch
    watch_item = WatchTender.new
    watch_item.tender_url = params[:tender_url]
    watch_item.user_id = current_user.id
    watch_item.save
    @tenderUrl = params[:tender_url]
    subscribe_tender(watch_item)
  end

  def remove_tender_watch_from_account
    remove_tender_watch()
    redirect_to :back
  end

  def remove_tender_watch
    tenders = WatchTender.where( :tender_url => params[:tender_url], :user_id => current_user.id )
    tenders.each do |watch_tender|
      watch_tender.destroy
    end
    @tenderUrl = params[:tender_url]
  end

  def subscribe_tender( tender_watch = nil ) 
    if tender_watch == nil
      #nothing passed so this must be coming from a view
      tender_watch = WatchTender.find(params[:tender_watch_id])
      @buttonID = params[:buttonID]
      @tender_watch_id = params[:tender_watch_id]
    end

    tender = Tender.where(:url_id => tender_watch.tender_url).first
    tender_watch.email_alert = true
    tender_watch.save
  end

  def unsubscribe_tender
    tender_watch = WatchTender.find(params[:tender_watch_id])
    @buttonID = params[:buttonID]
    @tender_watch_id = params[:tender_watch_id]
    tender_watch.email_alert = false
    tender_watch.save
  end

  def search_via_saved
    search = Search.find(params[:search_id])
    rebuild_search( search.searchtype, search.search_string )
    @search = search
    @search.last_viewed = DateTime.now
    @search.has_updated = false
    @search.save
  end

  def rebuild_search(searchType, searchString)
    if not searchType
      searchType = params[:searchtype]
      searchString = params[:searchString]   
    end

    if searchType == "tender"
      searchParams = QueryHelper.buildTenderSearchParamsFromString(searchString)
      searchParams[:controller] = "tenders"
      searchParams[:action] = "search"
    elsif searchType == "supplier"
      searchParams = QueryHelper.buildSupplierSearchParamsFromString(searchString)
      searchParams[:controller] = "organizations"
      searchParams[:action] = "search"
    else
      searchParams = QueryHelper.buildProcurerSearchParamsFromString(searchString)
      searchParams[:controller] = "organizations"
      searchParams[:action] = "search_procurer"
    end
    redirect_to searchParams
  end

  def newCPVGroup
    @userID = params[:user_id]
  end
  
  def sendAlert
    search = Search.find(params[:search_id])
    AlertMailer.search_alert(current_user,search).deliver
  end

  def sendTenderAlert
    tender = Tender.find(params[:tender_id])
    attributes = ["estimated_value", "test", "procurring_entity_id"]
    AlertMailer.tender_alert(current_user,tender,attributes).deliver
  end

  def create_group
    user = User.find(params[:user_id])
    group = CpvGroup.new
    group.user_id = user.id
    group.name = params[:name]
    group.save
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  # POST /resource
  def create
    build_resource
    resource.role = "user"
    if resource.save
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_in(resource_name, resource)
        respond_with resource, :location => after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end


end

app/controllers/users/sessions.rb
class Users::SessionsController < Devise::SessionsController
  before_filter :authenticate_user!
  before_filter do |controller_instance|
  end

  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end


  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  def new
    @user = User.new
    puts "NEW"
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end


  def edit
    @user = User.find(params[:id])
    redirect_to users_path
  end


  def create
    user = params[:user]
    user[:role => "user"]
    puts "CREATE"
    @user = User.new(user)

    respond_to do |format|
      if @user.save
        format.html { redirect_to sers_path, notice: t('app.msgs.success_created', :obj => t('app.common.user')) }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_path, notice: t('app.msgs.success_updated', :obj => t('app.common.user')) }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def new
    self.resource = build_resource(nil)
    clean_up_passwords(resource)
    respond_with(resource, serialize_options(resource))
  end

  # POST /resource/sign_in
  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message(:notice, :signed_in) if is_navigational_format?
    sign_in(resource_name, resource)
    respond_with resource, :location => after_sign_in_path_for(resource)
  end

# DELETE /resource/sign_out
  def destroy
    redirect_path = after_sign_out_path_for(resource_name)
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    set_flash_message :notice, :signed_out if signed_out && is_navigational_format?

    # We actually need to hardcode this as Rails default responder doesn't
    # support returning empty response on GET request
    respond_to do |format|
      format.any(*navigational_formats) { redirect_to redirect_path }
      format.all do
        head :no_content
      end
    end
  end
end

app/views/user/_cpvGroups.html.erb
<div class="AddCPVGroup">
  <%= render :partial => "user/cpv_create_button" %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th class="header-5"></th>
      <th class="header-7"></th>
      <th><%=t("Name")%></th>
      <th><%=t("Date Saved")%></th>
  </thead>
  <tbody>
    <% @cpvGroups.each do |cpvGroup| %>
      <tr>
        <td><%= link_to(image_tag("delete-icon.png"), {:controller => "cpv_tree", :action => "deleteCPVTree", :cpvGroup => cpvGroup, :isGlobal => @isGlobal}, :class => "confirm") %></td>
        <td><%= button_to t("Edit"), {:controller => "cpv_tree", :action => "editCPVTree", :cpvGroup => cpvGroup, :isGlobal => @isGlobal}, :class => "user-button" %></td>
        <td><%= cpvGroup.name %></td>
        <td><%= cpvGroup.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/user/_cpv_create_button.html.erb
<%= button_to t("Add New Category"), {:controller => "cpv_tree", :action => "showCPVTree", :isGlobal => @isGlobal}, :class => "submit-button" %>

app/views/user/_cpv_create_form.html.erb
<%= form_tag( {:controller => :user, :action => "create_group",:user_id => @userID }, :remote => true) do %>
  <%= label_tag(:name, "Group Name:") %>
  <%= text_field_tag(:name) %>
  <%= submit_tag("new group") %>
<% end %>

app/views/user/_cpv_edit_remove.erb
<%= button_to t("Remove Category"), {:controller => "cpv_tree", :action => "deleteCPVTree", :cpvGroup => cpvGroup, :referrer => referrer} %>
<%= button_to t("Edit Category"), {:controller => "cpv_tree", :action => "editCPVTree", :cpvGroup => cpvGroup, :referrer => referrer} %>

app/views/user/add_tender_watch.js.erb
$(function () {
  $(".tender_subscription").html("<%= escape_javascript( button_to "Remove from Profile", {:controller => :user, :action => "remove_tender_watch", :tender_url => @tenderUrl}, :remote => true, :class => "user-button") %>");
  return false;
});

app/views/user/index.html.erb
<% title t("Account Page") %>


<h1><%=t("Account Page")%></h1>

<div class="vertical-tabs">
  <ul>
    <li><a href="#tabs-1"><%=t("Tenders")%></a></li>
    <li><a href="#tabs-2"><%=t("Suppliers")%></a></li>
    <li><a href="#tabs-3"><%=t("Procurers")%></a></li>
    <li><a href="#tabs-4"><%=t("Searches")%></a></li>
    <li><a href="#tabs-5"><%=t("Custom CPV Categories")%></a></li>
  </ul>
  <div id="tabs-1">
    <h3><%=t("Tenders You Are Watching")%></h3>
    <table class="table table-striped">
      <thead>
        <tr>
          <th class="header-5"></th>
          <% if not Rails.application.config.live_deploy %>
            <th class="header-15"></th>
          <%end%>
          <th><%=t("Name")%></th>
          <th><%=t("Type")%></th>
          <th><%=t("Status")%></th>
          <th><%=t("Estimated Value")%></th>
          <th><%=t("Date Saved")%></th>
        </tr>
      </thead>
      <tbody>
        <% count = 0 %>
        <% @watched_tenders.each do |watch_tender| %>
          <% count = count + 1 %>
          <% buttonID = "tender_watch_button_"+count.to_s %>
          <% highlightClass = "" %>
            <% tender = Tender.where(:url_id => watch_tender.tender_url ).first %>
            <% highlights = nil %>
            <% if watch_tender.has_updated %>
              <% highlights = watch_tender.hash %>
            <% end %>
          <% if watch_tender.has_updated %>
            <% highlightClass = 'class="bidwinner"'.html_safe %>
          <% end %>
          <tr>
            <td <%=highlightClass%>><%= link_to(image_tag("delete-icon.png", :size => "30x30"), {:action => "remove_tender_watch_from_account", :tender_url => tender.url_id}, :class => "confirm") %></td>

            <% if not Rails.application.config.live_deploy %>
              <% if watch_tender.email_alert %>  
              <td <%=highlightClass%>><div <%= "id = "+buttonID %> ><%= button_to t("Unsubscribe"), {:action => "unsubscribe_tender", :tender_watch_id => watch_tender.id, :buttonID => buttonID}, :remote => true, :class => "user-button"%></div></td>
              <% else %>
                <td <%=highlightClass%>><div <%= "id = "+buttonID %> ><%= button_to t("Subscribe"), {:action => "subscribe_tender", :tender_watch_id => watch_tender.id, :buttonID => buttonID}, :remote => true, :class => "user-button" %></div></td>
              <% end %>
            <%end%>

            <td <%=highlightClass%>><%= link_to tender.tender_registration_number, tender_path(:id => tender.id, :highlights => highlights) %></td>
            <td <%=highlightClass%>><%= t(tender.tender_type.strip) %></td>
            <td <%=highlightClass%>><%= t(tender.tender_status) %></td>
            <td <%=highlightClass%>><%= number_to_currency(tender.estimated_value, :unit => "GEL ") %></td>
            <td <%=highlightClass%>><%= watch_tender.created_at %></td>
           
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div id="tabs-2">
    <h3><%=t("Suppliers You Are Watching")%></h3>
    <table class="table table-striped">
      <thead>
        <tr>
          <th class="header-5"></th>
          <% if not Rails.application.config.live_deploy %>
            <th class="header-15"></th>
          <%end%>
          <th><%=t("Name")%></th>
          <th><%=t("Date Saved")%></th>
        </tr>
      </thead>
      <tbody>
        <% count = 0 %>
        <% @watched_suppliers.each do |watch_supplier| %>
          <% count = count + 1 %>
          <% buttonID = "supplier_watch_button_"+count.to_s %>
          <% highlightClass = "" %>
          <% if watch_supplier.has_updated %>
            <% highlightClass = 'class="bidwinner"'.html_safe %>
          <% end %>
          <tr>
            
            <td <%=highlightClass%> ><%= link_to(image_tag("delete-icon.png", :size => "30x30"), {:action => "remove_supplier_watch_from_account", :supplier_watch_id => watch_supplier.id}, :class => "confirm") %></td>

            <% if not Rails.application.config.live_deploy %>
              <% if watch_supplier.email_alert %>
                <td <%=highlightClass%>><div <%= "id = "+buttonID %> ><%= button_to t("Unsubscribe"), {:action => "unsubscribe_supplier", :supplier_watch_id => watch_supplier.id, :buttonID => buttonID}, :remote => true, :class => "user-button" %></div></td>
              <% else %>
                <td <%=highlightClass%>><div <%= "id = "+buttonID %> ><%= button_to t("Subscribe"), {:action => "subscribe_supplier", :supplier_watch_id => watch_supplier.id, :buttonID => buttonID}, :remote => true, :class => "user-button" %></div></td>
              <% end %>
            <%end%>
            <% supplier = Organization.find(watch_supplier.supplier_id )%>
            <% highlights = nil %>
            <% if watch_supplier.has_updated %>
              <% highlights = watch_supplier.hash %>
            <% end %>
            <td <%=highlightClass%>><%= link_to supplier.name, organization_path(:id => supplier.id, :highlights => highlights) %></td>
            <td <%=highlightClass%>><%= watch_supplier.created_at %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div id="tabs-3">
    <h3><%=t("Procurers You Are Watching")%></h3>
    <table class="table table-striped">
      <thead>
        <tr>
          <th class="header-5"></th>
          <% if not Rails.application.config.live_deploy %>
            <th class="header-15"></th>
          <%end%>
          <th><%=t("Name")%></th>
          <th><%=t("Date Saved")%></th>
        </tr>
      </thead>
      <tbody>
        <% count = 0 %>
        <% @watched_procurers.each do |watch_procurer| %>
          <% count = count + 1 %>
          <% buttonID = "procurer_watch_button_"+count.to_s %>
          <% highlightClass = "" %>
          <% if watch_procurer.has_updated %>
            <% highlightClass = 'class="bidwinner"'.html_safe %>
          <% end %>
          <tr>
            <td <%=highlightClass%>><%= link_to(image_tag("delete-icon.png", :size => "30x30"), {:action => "remove_procurer_watch_from_account", :procurer_watch_id => watch_procurer.id}, :class => "confirm") %></td>

            <% if not Rails.application.config.live_deploy %>
              <% if watch_procurer.email_alert %>
                <td <%=highlightClass%>><div <%= "id = "+buttonID %> ><%= button_to t("Unsubscribe"), {:action => "unsubscribe_procurer", :procurer_watch_id => watch_procurer.id, :buttonID => buttonID}, :remote => true, :class => "user-button" %></div></td>
              <% else %>
                <td <%=highlightClass%>><div <%= "id = "+buttonID %> ><%= button_to t("Subscribe"), {:action => "subscribe_procurer", :procurer_watch_id => watch_procurer.id, :buttonID => buttonID}, :remote => true, :class => "user-button" %></div></td>
              <% end %>
            <%end%>
            <% procurer = Organization.find(watch_procurer.procurer_id )%>
            <% highlights = nil %>
            <% if watch_procurer.has_updated %>
              <% highlights = watch_procurer.hash %>
            <% end %>
            <td <%=highlightClass%>><%= link_to procurer.name, {:controller => "organizations", :action => "show_procurer", :id => procurer.id, :highlights => highlights} %></td>
            <td <%=highlightClass%>><%= watch_procurer.created_at %></td>

          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div id="tabs-4">
    <h3><%=t("Your Saved Searches")%></h3>
    <table class="table table-striped">
      <thead>
        <tr>
          <th class="header-5"></th>
          <% if not Rails.application.config.live_deploy %>
            <th class="header-15"></th>
          <%end%>
          <th><%=t("Name")%></th>
          <th><%=t("Type")%></th>
          <th><%=t("Date Saved")%></th>
        </tr>
      </thead>
      <tbody>
        <% @savedSearches.each do |search| %>
          <% count = count + 1 %>
          <% buttonID = "tender_watch_button_"+count.to_s %>
          <% highlightClass = "" %>
           <% if search.has_updated %>
            <% highlightClass = 'class="bidwinner"'.html_safe %>
          <% end %>
          <tr>
            <td <%=highlightClass%>><%= link_to(image_tag("delete-icon.png", :size => "30x30"), {:action => "remove_search_from_account", :search_id => search.id}, :class => "confirm") %></td>
          
            <% if not Rails.application.config.live_deploy %>
              <% if search.email_alert %>
                <td <%=highlightClass%>><div id="<%= buttonID %>"> <%= button_to t("Unsubscribe"), {:action => "unsubscribe_search", :search_id => search.id, :buttonID => buttonID}, :remote => true, :class => "user-button" %></div></td>
              <% else %>
                <td <%=highlightClass%>><div id="<%= buttonID %>"> <%= button_to t("Subscribe"), {:action => "subscribe_search", :search_id => search.id, :buttonID => buttonID}, :remote => true, :class => "user-button" %></div></td>
              <% end %>
            <%end%>
            <td <%=highlightClass%>><%= link_to search.name, :controller => "user", :action => "search_via_saved", :search_id => search.id %></td>
            <td <%=highlightClass%>><%= search.searchtype %></td>
            <td <%=highlightClass%>><%= search.created_at %></td>

          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div id="tabs-5">
    <h3><%=t("Your CPV Groups")%></h3>
<%= render :partial => "user/cpvGroups", :locals => {:cpvGroups => @cpvGroups, :referrer => "user"} %>
  </div>
</div>

</div>

app/views/user/newCPVGroup.js.erb
$(function () {
  $(".AddCPVGroup").html("<%= escape_javascript( render :partial => "user/cpv_create_form" ) %>");
  return false;
});

app/views/user/remove_procurer_watch.js.erb
$(function () {
  $(".procurer_subscription").html("<%= escape_javascript( button_to "Save to Profile", {:controller => :user, :action => "add_procurer_watch", :procurer_id => @organization.id }, :remote => true, :class => "user-button") %>");
  return false;
});

app/views/user/remove_tender_watch.js.erb
$(function () {
  $(".tender_subscription").html("<%= escape_javascript( button_to "Save to Profile", {:controller => :user, :action => "add_tender_watch", :tender_url => @tenderUrl }, :remote => true, :class => "user-button") %>");
  return false;
});

app/views/user/save_search.js.erb
$(function () {
  $(".search_serialization").html("<%= escape_javascript( render :partial => "user/remove_form" ) %>");
  return false;
});

app/views/user/subscribe_search.js.erb
$(function () {
  alert("test");
  $("<%= "#"+@buttonID %>").html("<%= escape_javascript( button_to "Unsubscribe", {:action => "unsubscribe_search", :search_id => @searchID, :buttonID => @buttonID}, :remote => true,:class => "user-button") %>");
  return false;
});

app/views/user/subscribe_supplier.js.erb
$(function () {
  $("<%= "#"+@buttonID %>").html("<%= escape_javascript( button_to t("Unsubscribe"), {:action => "unsubscribe_supplier", :supplier_watch_id => @supplier_watch_id, :buttonID => @buttonID}, :remote => true,:class => "user-button") %>");
  return false;
});

app/views/user/unsubscribe_supplier.js.erb
$(function () {
  $("<%= "#"+@buttonID %>").html("<%= escape_javascript( button_to t("Subscribe"), {:action => "subscribe_supplier", :supplier_watch_id => @supplier_watch_id, :buttonID => @buttonID}, :remote => true,:class => "user-button" ) %>");
  return false;
});

app/views/user/unsubscribe_tender.js.erb
$(function () {
  $("<%= "#"+@buttonID %>").html("<%= escape_javascript( button_to "Subscribe", {:action => "subscribe_tender", :tender_watch_id => @tender_watch_id, :buttonID => @buttonID}, :remote => true,:class => "user-button" ) %>");
  return false;
});