config/routes.rb
BootstrapStarter::Application.routes.draw do

	#--------------------------------
	# all resources should be within the scope block below
	#--------------------------------
	scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

		match '/admin', :to => 'admin#index', :as => :admin, :via => :get
    match '/user', :to => 'user#index', :as => :user, :via => :get
  
		 devise_for :users, :controllers => { :sessions => "users/sessions", :registrations => "users/registrations" }, :path_names => { :sign_up => "register" }

    namespace :admin do
      resources :users
    end

    resources :tenders
    resources :organizations

    match '/organization/search_procurer' => 'organizations#search_procurer'
    match '/organization/search' => 'organizations#search'
    match '/organization/getProcurers' => 'organizations#getProcurers'
    match '/organization/getSuppliers' => 'organizations#getSuppliers'
    match '/root/organization/search_procurer' => 'organizations#search_procurer'
    match '/root/organization/search' => 'organizations#search'

    match '/tender/search' => 'tenders#search'
    match '/tender/search_via_saved' => 'tenders#search_via_saved'
    match '/tender/download' => 'tenders#download'
    match '/organization/download_proc_tenders' => 'organizations#download_proc_tenders'
    match '/organization/download_org_tenders' => 'organizations#download_org_tenders'
    match '/tenders/index' => 'tenders#index'
    match '/procurer' => 'organizations#show_procurer'
    match '/watch_tender/subscribe' => 'watch_tender#subscribe'
    match '/watch_tender/unsubscribe' => 'watch_tender#unsubscribe'
    match '/cpv_tree/showCPVtree' => 'cpv_tree#showCPVTree'
    match ':controller/:action'
    match '/build_user_data', :to => 'root#build_user_data', :as => :build_user_data, :via => :get
    match '/generate_cpv_codes', :to => 'root#generate_cpv_codes', :as => :generate_cpv_codes, :via => :get
    match '/:locale' => 'root#index'		
    root :to => 'root#index'
	  
	end

	match '', :to => redirect("/#{I18n.default_locale}") # handles /
	
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    

    <!-- CSS CNDs -->
    <link href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/smoothness/jquery-ui.min.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- JS CNDs -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
    <script src="//ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.0/jquery.dataTables.min.js"></script> 
    <script src="//code.highcharts.com/stock/highstock.js"></script>
    <script src="//code.highcharts.com/stock/highcharts-more.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.1.6/d3.min.js"></script>


    <%= javascript_include_tag "application" %>
		<script type="text/javascript">
			I18n.defaultLocale = "<%= I18n.default_locale %>";
			I18n.locale = "<%= I18n.locale %>";
		</script>

    <!-- Javascripts
    ================================================== --> 

		<% if Rails.env.production? %>
			<script>
				(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
				(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
				m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
				})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

				ga('create', 'UA-41736303-1', 'tendermonitor.ge');
				ga('send', 'pageview');
			</script>
		<% elsif Rails.env.staging? %>
			<!-- insert google analytics for staging site here -->
		<% end %>

    <title><%= content_for?(:title) ? "#{yield(:title)} > #{t('app.common.app_name')}" :
				t('app.common.app_name') %></title>
    <%= csrf_meta_tags %>


    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

		<!--[if IE 6]><%= stylesheet_link_tag 'ie6' %><![endif]-->
	  <!--[if IE 7]><%= stylesheet_link_tag 'ie7' %><![endif]-->

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag '/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
   <div id="wrap">
    <div class="main-menu" style="height: 70px">
      <div class="container" style="height: 100%">
        <div class="heading" style="height: 100%">
          <div class="row-fluid" style="height: 100%">
            <div class="span8" style="height: 100%">
              <a href=<%=root_path(:locale => I18n.locale)%> style="text-decoration: none"><h1 class="heading"><%=t("site_title")%> <span class="beta-text">Beta</span></h1></a>
              
            </div>
            <div class="span4" style="height: 100%">
              <%= link_to(image_tag(t("logo_path")), t("logo_url"), :target => "_blank", :title => t(".ti_link_title"), :class => "banner"	) %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="navigation-menu">
      <div class="container">
        <div class="row-fluid parent-block"> 
          <div class="span2">
            <%= link_to( t("Search Page"), root_path(:locale => I18n.locale),:class=>"nav-item") %>
          </div>
          <div class="span3">
            <%= link_to( t("Annual Data"), {:controller => '/analysis', :action => "index"}, :class=>"nav-item") %>
          </div>
          <div class="span2">
						<%= link_to( t("About"), {:controller => '/root', :action => "about"}, :class=>"nav-item") %>
          </div>
          <div class="span3 offset1">
            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle nav-item" data-toggle="dropdown" >
                    <%= current_user.email %>
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li>
       		         <%= link_to t("Account"), user_path %>
				          </li>
                  <% if current_user.role == 'admin' %>
                    <li>
       		            <%= link_to t("Admin"), admin_path %>
				            </li>
                  <% end %>
                  <li>
       		         <%= link_to t('.sign_out'), destroy_user_session_path %>
				          </li>
                </ul>
              </li>
            <% else %>
               <%= link_to t("Sign In"), new_user_session_path, :class=>"nav-item" %>
            <% end %>
          </div>

          <div class="span1">
	          <% I18n.available_locales.each do |locale| %>
		          <% if locale != I18n.locale %>
			          <%= link_to t("app.language.#{locale}"), params.merge(:locale => locale) %>
		          <% end %>
	          <% end %>
          </div>
        </div>
      </div>
    </div>

    <div id="content"><%= content_for?(:content) ? yield(:content) : yield %></div>

    <div id="push"></div>
  </div>
  <div id="footer">
    <div class="container">
      <%= link_to(image_tag("sida_logo.gif", :size => "100x100"), "http://www.sida.se/English/", :target => "_blank"	) %>
      <%= link_to(image_tag("slovak_aid_logo.gif", :size => "125x100" ), "http://eng.slovakaid.sk/", :target => "_blank"	) %>
      <%= link_to(image_tag("spa-logo.jpg", :size => "300x100" ), t("spa_logo_link"), :target => "_blank", :style => "float: right;"	) %>
    </div>
   </div>

  <div id="dialog-confirm" title="Delete?">
  <p><span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>This item will be permanently deleted, Are you sure?</p>
  </body>

</html>

app/views/layouts/full-screen.html.erb
<% content_for :content do %>
  <%= yield %>
<% end %>
<%= render :template => 'layouts/application' %>

app/views/layouts/standard.html.erb
<% content_for :content do %>
  <div class="main-content container">
    <div class="content">
      <div class="row">
         <div class="span12">
			    <% flash.each do |key, msg| %>
				    <div class="alert <%= flash_translation(key) %> fade in">
					    <a href="#" data-dismiss="alert" class="close">×</a>
					    <%= msg %>
				    </div>
			    <% end %>

          <%= yield %>
        </div><!--/span-->
      </div><!--/row-->
    </div><!--/content-->
  </div>
<% end %>
<%= render :template => 'layouts/application' %>

app/views/layouts/unsupported_browser.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? "#{yield(:title)} > #{t('app.common.app_name')}" :
				t('app.common.app_name') %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <!--[if IE 6]><%= stylesheet_link_tag 'ie6' %><![endif]-->
    <!--[if IE 7]><%= stylesheet_link_tag 'ie7' %><![endif]-->

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag '/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to(t('app.common.app_name'), root_path(:locale => I18n.locale),:class=>"brand")%>
          <div class="container nav-collapse">
            <ul class="nav pull-right">
  						<% I18n.available_locales.each do |locale| %>
  							<% if locale != I18n.locale %>
  								<li><%= link_to t("app.language.#{locale}"), params.merge(:locale => locale) %></li>
  							<% end %>
  						<% end %>
            </ul>
	        </div>
        </div>
      </div>
    </div>

		<div id="wrapper">
		  <div class="container">
		    <div class="content">
		      <div class="row">
		       <div class="span12">

		          <div class="page-header">
		            <h1>
									<%= t('.title') %>
								</h1>
							</div>

								<p><%= t('.p1') %></p>
								<p><%= t('.p2') %></p>
								<ul class="standard">
									<li>
										<a href="http://www.google.com/chrome/"><%= t('.chrome') %></a>
									</li>
									<li>
										<a href="http://www.mozilla.org/firefox/new/"><%= t('.firefox') %></a>
									</li>
									<li>
										<a href="http://windows.microsoft.com/en-US/internet-explorer/downloads/ie/"><%= t('.ie') %></a>
									</li>
									<li>
										<a href="http://www.opera.com/download/"><%= t('.opera') %></a>
									</li>
									<li>
										<a href="http://support.apple.com/downloads/#internet"><%= t('.safari') %></a>
									</li>
								</ul>
		        </div>
		      </div><!--/row-->
		    </div><!--/content-->
		  </div> <!-- /container -->
      <div class="push"><!--//--></div>
    </div><!--/wrapper-->


	<% if Rails.env.production? %>
		<!-- google analytics -->
	<% elsif Rails.env.staging? %>
		<!-- google analytics -->
	<% end %>

  </body>
</html>